version: '3'

services:
  app:
    build: .
    container_name: openraffle_app
    command: sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - .:/home/openraffle/app
    depends_on:
      - db

  db:
    image: postgres:12.2
    container_name: openraffle_db
    tty: true
    volumes:
      - openraffle-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=openraffle
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres

volumes:
  openraffle-volume:
    external: true
