[tool.black]
line-length = 89
include = '\.pyi?$'
exclude = '''
(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    |  base_backend/asgi\.py
    |  base_backend/wsgi\.py
    | .*/migrations/.*\.py
    | manage\.py
    | _build
    | buck-out
    | build
    | dist
)
'''