# Generated by Django 3.2.3 on 2021-05-31 20:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Raffle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data de atualização"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="valor por ponto",
                    ),
                ),
                ("raffle_date", models.DateField(verbose_name="data do sorteio")),
                (
                    "amount",
                    models.PositiveSmallIntegerField(
                        default=50, verbose_name="quantidade de pontos"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "rifa",
            },
        ),
        migrations.CreateModel(
            name="RaffleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data de atualização"
                    ),
                ),
                ("item", models.PositiveSmallIntegerField(verbose_name="ponto")),
                ("winner", models.BooleanField(default=False, verbose_name="ganhador")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "raffle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="raffle.raffle",
                        verbose_name="rifa",
                    ),
                ),
            ],
            options={
                "verbose_name": "ponto",
                "unique_together": {("raffle", "item")},
                "index_together": {("raffle", "item")},
            },
        ),
    ]
